### ISSUE TITLE
Support for XSAVES needed for Windows 10 Redstone / Skylake

### ISSUE THREAD

**Issue by ionescu007** [tandasat/HyperPlatform#13]
Hi,

Intel Skylake processors add new XSAVES instruction, and Windows 10 Redstone kernel makes use of it if available. Currently, hyperplatform does not enable XSAVES support in the guest, meaning the instruction will generate #UD.

Please set enable_xsaves_xstors to true in  secondary controls, in order to avoid this issue.

**Comment by tandasat** [comment]
Thank you for reporting the issue with a right reference. That is very helpful. I have fixed it with 7dc4e68 so please test and let me know if that works.

**Comment by ionescu007** [comment]
Works for me.
