### ISSUE TITLE
AMD-V Support

### ISSUE THREAD

**Issue by tandasat** [tandasat/HyperPlatform#2]
AMD provides hardware based virtualization called AMD-V. Although it is similar to that of Intel (Intel VT-x) in both programming-wise and functionality-wise, supporting AMD-V practically requires a physical device. Also, given lower popularity of ADM processors, support of AMD-V is not planned currently.

**Comment by BackDoorManUC** [comment]
would be cool if there was a library abstracting Intel VT-x and AMD-V (SVM) so a single codebase could be used to support both Intel and AMD
