### ISSUE TITLE
No CPL Checks for Privileged Instructions

### ISSUE THREAD

**Issue by ionescu007** [tandasat/HyperPlatform#28]
Hi,

Many exit handlers for privileged instructions, such as XSETBV, MSR, IN/OUT, do not do appropriate checks for CPL and/or IOPL. As such, with HyperPlatform running, guest user-mode code is allowed to bypass ring permissions.

**Comment by hzqst** [comment]
yes, I found that most hypervisors have this problem.

**Comment by alexalexroro** [comment]
Well actually if you open the Intel Software Developer Manual Vol3 and go to section "25.1.1 Relative Priority of Faults and VM Exits" you could see that you will not receive VM exits on instructions which fail privilege checks - these will generate GP exceptions.
So there shouldn't be in any hypervisor checks for privilege levels on exits on privileged instructions.

**Comment by tandasat** [comment]
Hi, Sorry for the delayed reply. 

Can you provide sample code and steps to confirm the issue? As @alexalexroro pointed out, my understanding is that privilege check takes place prior to VM-exit, and below code caused STATUS_PRIVILEGED_INSTRUCTION exception regardless of existence of HyperPlatform. It seemed to support my understanding.
```
#include "stdafx.h"
#include <Windows.h>
#include <intrin.h>
#include <stdio.h>

int main() {
  __try {
    unsigned char c = __inbyte(0);
    printf("__inbyte %02hx\n", c);
  } __except (EXCEPTION_EXECUTE_HANDLER) {
    printf("Exception %08x\n", GetExceptionCode());
  }
  return 0;
}
```
![status_privileged_instruction](https://cloud.githubusercontent.com/assets/1620923/18168430/75e44b0c-700a-11e6-97cf-56596ea2c1ad.png)
Tested on Win7 x64 with 32bit test program with elevated admini privileges.

**Comment by ionescu007** [comment]
It appears you're right on Intel systems. On AMD this is not always the case -- for example see https://bugzilla.redhat.com/show_bug.cgi?id=1284941. My bad :)

**Comment by tandasat** [comment]
No problem. 

I am rather curious how you found the bug report. This report made me think that I should not attempt to support AMD systems hastily. Seems straightforward; in fact, lots of details need to be aware of ;)

**Comment by esoterix** [comment]
I haven't tested it but it appears you don't do any privilege checks in VmmpHandleDrAccess. Refer to intel manual "25.1.3 Instructions That Cause VM Exits Conditionally":

> MOV DR. The MOV DR instruction [...] VM exit [...] takes priority over the following: general-protection exceptions based on privilege level; and invalid-opcode exceptions that occur because CR4.DE=1 and the instruction specified access to DR4 or DR5

Keep in mind that you should not advance the guest instruction pointer when injecting a #GP due to privilege level.

You can verify this by writing a usermode program that uses an instruction such as "mov dr7, 400h".

**Comment by tandasat** [comment]
@esoterix Thanks for flagging this up. Fixed it along with other DR register access improvement on fedf722d13fc79e39bf6f67fda62680541d2b34b.

Test code attached: [Issue28.zip](https://github.com/tandasat/HyperPlatform/files/2321534/Issue28.zip)
