### ISSUE TITLE
Triple Fault BSOD randomly

### ISSUE THREAD

**Issue by hzqst** [tandasat/HyperPlatform#32]
### Description

Latest HyperPlatform crash the system when running programs randomly.
### Expected behavior

the system should not crash.
### Actual behavior

the system crashed.
### Steps to reproduce the problem

I compiled the lastest HyperPlatform, and loaded it in vmware 12.0 Win7 x64 7600, then run some  programs. then the system went BSOD.
sometimes it even crashed when I did nothing(except loading the driver).
### Specifications
- Commit : 
- OS version Windows 7 7600
- Architecture: x64
- Hardware VMware 12
- Anything else:

`BUGCHECK_STR:  0xE2

PROCESS_NAME:  HipsDaemon.exe

CURRENT_IRQL:  2

ANALYSIS_SESSION_HOST:  HZQST-PC

ANALYSIS_SESSION_TIME:  09-19-2016 20:48:22.0815

ANALYSIS_VERSION: 10.0.10586.567 amd64fre

BAD_STACK_POINTER:  fffff88006ea6e98

LAST_CONTROL_TRANSFER:  from fffff8800397724f to fffff80003e88f00

STACK_TEXT:  
fffff880`06ea6e98 fffff880`0397724f : 00000000`000000e2 00000000`00000002 fffff880`06ea6f10 00000000`6e001010 : nt!KeBugCheckEx
fffff880`06ea6ea0 00000000`000000e2 : 00000000`00000002 fffff880`06ea6f10 00000000`6e001010 00000000`00000000 : HyperPlatform+0x424f
fffff880`06ea6ea8 00000000`00000002 : fffff880`06ea6f10 00000000`6e001010 00000000`00000000 00000000`00000000 : 0xe2
fffff880`06ea6eb0 fffff880`06ea6f10 : 00000000`6e001010 00000000`00000000 00000000`00000000 00000000`c0000100 : 0x2
fffff880`06ea6eb8 00000000`6e001010 : 00000000`00000000 00000000`00000000 00000000`c0000100 00000000`00000282 : 0xfffff880`06ea6f10
fffff880`06ea6ec0 00000000`00000000 : 00000000`00000000 00000000`c0000100 00000000`00000282 00000000`fffffff7 : 0x6e001010
`

what HyperPlatform+0x424f is in IDA
`if ( v6 == 2 )
      {
        VmmpDumpGuestSelectors();
        if ( !(_BYTE)KdDebuggerNotPresent )
          __debugbreak();
        KeBugCheckEx(0xE2u, 2ui64, v3, *(_QWORD *)(v3 + 16), 0i64);
      }`

what HyperPlatform+0x424f is in vmm.c

`case VmxExitReason::kTripleFault:
      VmmpHandleTripleFault(guest_context);
      break;`

`
// Triple fault VM-exit. Fatal error.
_Use_decl_annotations_ static void VmmpHandleTripleFault(
    GuestContext *guest_context) {
  VmmpDumpGuestSelectors();
  HYPERPLATFORM_COMMON_BUG_CHECK(HyperPlatformBugCheck::kTripleFaultVmExit,
                                 reinterpret_cast<ULONG_PTR>(guest_context),
                                 guest_context->ip, 0);
}
`

**Comment by tandasat** [comment]
Thanks for reporting the critical issue.  Is it possible to specify which program should be packed with which packer (and its configurations if it matters) to reproduce the issue as reliable as possible?

**Comment by hzqst** [comment]
Sorry my bad. I tried about 15 times and I found that every program would have 30% chance of BSOD instantly no matter whether it's protected or not.

**Comment by asamy** [comment]
@tandasat The issue has to do with your xsave/xrstor, removing it will bring everything back to normal.  They are currently useless.

**Comment by tandasat** [comment]
@asamy could you explain why did you know the offender is xsave/xrstor?

@hzqst thanks for re-checking. I was not able to find time to test by myself yet, but am hoping to address it as soon as I can reproduce by myself.

**Comment by hzqst** [comment]
@asamy thanks, I found that if I remove 
`  //VmmpSaveExtendedProcessorState(&guest_context);`
and
`  //VmmpRestoreExtendedProcessorState(&guest_context);`
, it will not crash anymore.

**Comment by tandasat** [comment]
@hzqst Thank you for testing a fix and reporting the result. That is interesting. @asamy To implement a proper fix, rather than just commenting it out without understanding the root cause, can you teach me why it is causing the issue? (sorry I has not been able to test it by myself yet)

**Comment by tandasat** [comment]
@hzqst I have been testing HP on a laptop (Win10 x64 build 160916-1700) but not been able to reproduce the issue yet. I am wondering if a processor generation could be relevant to it. Can you tell me what processors you use? 

Control Panel\System and Security\System shows "Code(TM) i7-4650U" in my case. 

Thank you.

**Comment by tandasat** [comment]
It would be helpful if you could provide more than one crash dump (MEMORY.DMP) files and a PDB file of a re-compiled HyperPlatform.sys with enabled kVmmpEnableRecordVmExit in vmm.cpp. 

To enable it, please set true to kVmmpEnableRecordVmExit, and a number of processors the system has to kVmmpNumberOfProcessors. This will record the last 100 VM-exits to g_vmmp_vm_exit_history per processor, and help me guess what the root cause of the issue. 

```
static const long kVmmpEnableRecordVmExit = false;

// How many events should be recorded per a processor
static const long kVmmpNumberOfRecords = 100;

// How many processors are supported for recording
static const long kVmmpNumberOfProcessors = 2;
```

Thank you for your help in advance.

**Comment by hzqst** [comment]
@tandasat dump & log files has been sent to your gmail.
I tried with `static const long kVmmpEnableRecordVmExit = true;` and got nothing after "The VMM has been installed." in HyperPlatform.log even if it crashed when `VmmpDumpGuestSelectors.` was called successfully.

It crashed instantly at `VmmpHandleTripleFault` after load driver if I don't comment out `//VmmpSaveExtendedProcessorState(&guest_context);
//VmmpRestoreExtendedProcessorState(&guest_context);`

It will not crash until I run any program if I comment out `//VmmpSaveExtendedProcessorState(&guest_context);
//VmmpRestoreExtendedProcessorState(&guest_context);`
 , and this program I run will be scanned by HipsDaemon.exe, a security software. 
in crash dump you can see that the crash happened in HipsDaemon.exe

**Comment by tandasat** [comment]
Thank you for the files and the additional details. I am mostly offline for the next two weeks but will get back to you when I made any progress on it. Thanks for being patient.

**Comment by asamy** [comment]
@hzqst A triple fault actually comes from the guest not inside root, and that happens when a double fault occurs inside guest, so it's irrelevant.

In fact, xsave/xrstor vm-exit barely happens.  So, it might also be the cause, assume the following scenario:

VM exit -> xsave -> exit reason is xsave/xrstor (you already opt that in in secondary control to enable there uses) -> VmmpHandleUnexpectedExit[?] -> welp.

However, I think it might be just the fact that you corrupt the state of FPU (e.g. it has already been used or similar).  I also think that the processor takes care of this anyway, besides why even care about FPU?  This will just slow stuff down, you're just supposed to handle stuff as-is inside a vm-exit and return control if authentic, etc.

I am not entirely sure why this happens, as I have not attempted to debug it, but it just seemed pointless to have those, so that's what made me think they are the cause.

**Comment by hzqst** [comment]
@asamy yes you're right, when I disabled xsaves_xstors exiting in secondary controls, it works fine with my Win7 and Win8 vmware, but somtimes failed with Win10 and the dump file said `FAULTING_IP: 
nt!SwapContext+a9
fffff800`685d4529 0fc729          xsaves  [rcx]
`
and `nt!KiInvalidOpcodeFault+0x106`
It is obvious that xsaves_xstors is used by Win10 kernel (if CPU support) and if you don't handled xsaves_xstors exiting it just raise an invalid opcode exception (#UD)  then crash the kernel.

**Comment by asamy** [comment]
Actually, I don't zeroing out `XSS_EXIT_BITMAP` matters, VMCS is zeroed out in whole anyway.  Have you tested it?

**Comment by tandasat** [comment]
I recently tested on VMware+Win10 and Win7 on 7th generation cores, but still I was not able to see the issue (regardless of whether `XSS_EXIT_BITMAP` is explicitly zeroed or not). 

I am still hoping to know the cause, but workaround we know so far is to comment out `VmmpSaveExtendedProcessorState(&guest_context);` and `VmmpRestoreExtendedProcessorState(&guest_context);` in `VmmVmExitHandler()`, is that correct? If you do so, it is also important to make sure you do not use XMM registers at all in VMM.

**Comment by asamy** [comment]
@tandasat Why not also provide backward compatibility by manually saving them?  Considering your using C++, so it's likely that compiler will trigger XMM in some way, somehow like my IRQ handler, here:

```asm
        /* Save XMM non-volatiles:  */
        movaps  %xmm0, KFRAME_XMM0(%rbp)
        movaps  %xmm1, KFRAME_XMM1(%rbp)
        movaps  %xmm2, KFRAME_XMM2(%rbp)
        movaps  %xmm3, KFRAME_XMM3(%rbp)
        movaps  %xmm4, KFRAME_XMM4(%rbp)
        movaps  %xmm5, KFRAME_XMM5(%rbp)```

```asm
        movaps KFRAME_XMM0(%rbp), %xmm0
        movaps KFRAME_XMM1(%rbp), %xmm1
        movaps KFRAME_XMM2(%rbp), %xmm2
        movaps KFRAME_XMM3(%rbp), %xmm3
        movaps KFRAME_XMM4(%rbp), %xmm4
        movaps KFRAME_XMM5(%rbp), %xmm5```

**Comment by tandasat** [comment]
@asamy Oh, does the issue disappear in that way? I might missed your comments if you have already mentioned it, sorry. The initial motivation of preserving XMM registers was, indeed, to deal with unintended use of XMM registers from C++ code, so that way seems ideal solution to the issue.

**Comment by asamy** [comment]
No, this is the first time I mentioned it, but I think if you want a good solution, then a good way is just saving volatile XMM registers which also achieves backward compatibility to processors with no support for XSAVES/XRSTORS.

**Comment by tandasat** [comment]
Agreed, and only XMM0-5 need to be saved. 
https://msdn.microsoft.com/en-us/library/9z1stfyw.aspx

Can you make pull request for that fix?

**Comment by asamy** [comment]
Sure, I will send you a patch soon enough.

**Comment by tandasat** [comment]
Thank you @asamy. Pushed your changes 34e12ffeb4a3d403f94447e548de2e745192ddbb, with fix for x86. 

@hzqst could you test with the fix on the branch issue32?
https://github.com/tandasat/HyperPlatform/tree/issue32

Thank you,

**Comment by hzqst** [comment]
Tested, It never crashes with branch issue32.

**Comment by tandasat** [comment]
That's great news! Merged into master

Thank you for testing and helping find a right fix @hzqst  and @asamy.
