### ISSUE TITLE
Support VT-x nesting?

### ISSUE THREAD

**Issue by hzqst** [tandasat/HyperPlatform#33]
Can HyperPlatform work(nest) with other VT-x/EPT project except VMware and VirtualBox?

I tried HyperPlatform with some VT-x projects and all of them crashed the vmware's virtual CPU while initializing.
it even crashed when I tried to load HyperPlatform twice.

**Comment by tandasat** [comment]
Hi, 

No. HyperPlatform works inside VMware or any VMs supporting virtualized VT-x, but not with any hypervisors including HyperPlatform is self. 

This is by design at this time, but there is an enhancement request for this design limitation (https://github.com/tandasat/HyperPlatform/issues/14).
