### ISSUE TITLE
Set CRx ReadShadow mask causes unhandled vmexit 33(invalid guest state) in windows x86.

### ISSUE THREAD

**Issue by hzqst** [tandasat/HyperPlatform#40]
### Description

Set some bits to 1 in CR0 / CR4 read shadow mask may cause unhandled vm-exit with exit reason 33 (VmxExitReason::kInvalidGuestState), Windows x86 only.

That's because some bits in CR0/ CR4 can not be modified casually, 

> VMX-FIXED BITS IN CR0

 said that bit of CRx is fixed to 0 in kIa32VmxCrxFixed0, and bit of CRx is fixed to 1 in kIa32VmxCrxFixed1, and you should follow these rules when MOV to CR0/CR4. if you don't, the CRx value might be invalid and an invalid guest state vm-exit could be issued.

### How to fix

Plan A : (quick fix)
 Comment the `UtilVmWrite(VmcsField::kGuestCr0, *register_used);` in `VmmpHandleCrAccess`
 Comment the `UtilVmWrite(VmcsField::kGuestCr4, *register_used);` in `VmmpHandleCrAccess`

Plan B (better) :

use
```
		  const Cr0 cr0_fixed0 = { UtilReadMsr(Msr::kIa32VmxCr0Fixed0) };
		  const Cr0 cr0_fixed1 = { UtilReadMsr(Msr::kIa32VmxCr0Fixed1) };
		  Cr0 cr0 = { *register_used };
		  cr0.all &= cr0_fixed1.all;
		  cr0.all |= cr0_fixed0.all;

          UtilVmWrite(VmcsField::kGuestCr0, cr0.all);
          UtilVmWrite(VmcsField::kCr0ReadShadow, cr0.all);
```

instead of simply writing `*register_used` to guest CR0 & CR0 read shadow in `VmmpHandleCrAccess`.

the CR4 follows the same way...

### Expected behavior

The driver should be loaded successfully and not be supposed to crash the system.

### Actual behavior

see the snapshots
![cr1](https://cloud.githubusercontent.com/assets/12287588/22425376/d037bff6-e735-11e6-84b4-25df687e02fd.png)
![cr4](https://cloud.githubusercontent.com/assets/12287588/22425377/d04a5c7e-e735-11e6-9203-0d67ea0f33c3.png)

`
// Unexpected VM-exit. Fatal error.
_Use_decl_annotations_ static void VmmpHandleUnexpectedExit(
    GuestContext *guest_context) {
  VmmpDumpGuestSelectors();
  HYPERPLATFORM_COMMON_BUG_CHECK(HyperPlatformBugCheck::kUnexpectedVmExit,
                                 reinterpret_cast<ULONG_PTR>(guest_context), 0,
                                 0);
}
`
code = 33

### Steps to reproduce the problem

1.Download the latest HyperPlatform-master branch source code.
2.Uncomment the `cr4_mask.fields.vmxe = true; `and `cr4_shadow.fields.vmxe = false; `in `VmpEnterVmxMode` just like the comment said `// For example, when we want to hide CR4.VMXE from the guest, comment in below`.
3.Compile the source code in x86/release config.
4.Load the driver.

### Specifications
- Commit : none

- OS version : Windows 7 sp1 (7601)
- Architecture: x86 only

- Hardware: Vmware 12

- Details:

**Comment by tandasat** [comment]
Thank you for reporting the issue with the detailed note and steps to repro. I was able to reproduce the issue and am going to fix it shortly. The proposed fixes are also helpful.

**Comment by tandasat** [comment]
I have tested and pushed your fixes. That should address the issue. 

Good catch, and thank you for proposing fixes!
