### ISSUE TITLE
System Crash on Insider Preview (170127-1750)

### ISSUE THREAD

**Issue by tandasat** [tandasat/HyperPlatform#41]
### Description

System occasionally crashes when HyperPlatform is loaded on an Insider preview version of Windows due to `kInvalidGuestState (0n33)`. This case, Guest's RIP points to the very first instruction in a guest (ie, `asmResumeVm`), indicating that guest setup is not done correctly and the guest did not run at all.

Some times HyperPlatform loads successfully, but subsequent execution of some applications fails doe to access violation. This might indicate that an issue is related to memory management settings (CR4, descriptor tables, EPT etc).

Confirmed on `Built by: 15025.1000.amd64fre.rs_prerelease.170127-1750`

### Expected behavior

HyperPlatform installs and run without breaking system behaviour.

### Actual behavior

System crashes, or some applications stop running properly after installation.

### Steps to reproduce the problem

Compile HyperPlatform for Debug x64
Loads the driver onto the insider preview version
System crashes, or DrvLoader.exe etc starts showing access violation errors.
![untitled](https://cloud.githubusercontent.com/assets/1620923/22595803/e4749304-e9dd-11e6-91a9-2281a491c9bf.png)
[log.txt](https://github.com/tandasat/HyperPlatform/files/750763/log.txt)

### Specifications
- Commit (eg, 2099af7): fd224aa  

- OS version (ie, outout of the "ver" command, or N/A): Microsoft Windows [Version 10.0.15025]

- Architecture: x64

- Hardware (eg, Physical, VMware 11, Bochs, or N/A): Physical, VMware 12

- Details:

Neither disabling `enable_ept` nor `descriptor_table_exiting` in `VmxProcessorBasedControls` helped.

**Comment by Kelvinhack** [comment]
Recently i had same vmexit reason due to the TSS busy bit is not set, not sure is it same problem.

**Comment by tandasat** [comment]
@Kelvinhack Interesting, could you provide an example of fix to try?

**Comment by Kelvinhack** [comment]
@tandasat you can just have a check Guest TR Ar Bytes bit2 is it set. Ensure it is set before vmlaunch or vmresume.

**Comment by Kelvinhack** [comment]
Edited: Bit 1 , supposed 64bit BUSY TSS is 1011B, so which should be 0x8B  in VMM AR bytes format.

**Comment by tandasat** [comment]
Thanks. It seems guest's TR had an expected value. See the last line in the attached log. The last column is the AR value.

`06:29:55.451	DBG	#0	    4	 3980	System         	tr 0040 FFFFF801E6A50000 00000067 0000008b`

**Comment by Kelvinhack** [comment]
Oh. Then may be it caused by other problem in Guest Field before Vmlaunch or resume

**Comment by Kelvinhack** [comment]
I would print all of Guest field .. before Vmresume then compared to intel sdm vm entry check

**Comment by tandasat** [comment]
- This issue happens even if `cr3_load_exiting`, `mov_dr_exiting`, `use_io_bitmaps`, `use_msr_bitmaps`, `enable_ept`, `descriptor_table_exiting`, and `enable_vpid` are set to false.
- The first core that is visualized often successes to enter VM, and the second core more often gets Invalid Guest State at the very first guest instruction. 
- Even VM started to run successfully, applications start crashing randomly. 
- Guest register base VMCS fields do not seem to be broken (values taken right before VMLAUNCH)
[diff.htm.txt](https://github.com/tandasat/HyperPlatform/files/753084/diff.htm.txt)

**Comment by Kelvinhack** [comment]
According to your second HTM file, I realized that FS Ar byte bit : 7 (0x4073 vs 0x40f3) has been modified by some one else? Intel seem require it always be 1 if the register is used. 

Moreover , according to your providing document , GDTR Limit seem always are 0x57 since every-time system crashs,  may be we should find out the reason?

btw, have you used IDA+GDB+VMWare for single stepping a VMM , it think it is good for tracing this problem ? As least it can single-stepping into VMLAUNCH/VMRESUME.

**Comment by tandasat** [comment]
I think GDTR limit is ok, as it is also 0x57 on the system before entering to a VM. FS Ar byte is a weird one, which I was not able to see how come it changed sometime, but even if AR was 0x40f3 (sometimes it is), a system still ran under unstable state I mentioned. Unconditionally setting 1 on the bit does not seem to affect to the bug either. 

Debugging VMware is an interesting approach I never thought of :) A challenge in this scenario is that `Invalid Guest State` vm-exit often does not happen immediately. It sounds challenging to me to catch the moment of the failure.

**Comment by Kelvinhack** [comment]
https://kelvinhack127.blogspot.com/2017/02/through-idavmware-for-debugging-any.html

 you can try it , and sometime it is useful for develop and debugging a VMM i think..... we can be able to single stepping VMRESUME and VMLAUNCH

**Comment by tandasat** [comment]
Very interesting, thank you for sharing the technique! Hopefully, I can avoid doing it for this bug (as debugging can be time consuming) but this technique seems quite useful under some circumstances.
