### ISSUE TITLE
EoPMon build failed due to commit b41f7e95065fbc69c29f4578ca849d30215f6ae3 

### ISSUE THREAD

**Issue by shsirk** [tandasat/HyperPlatform#42]
eopmon still needs HyperPlatform/kernel_stl.h which is removed in above commit.

**Comment by tandasat** [comment]
Thank you for reporting the issue. It should be fixed with below commits now:
https://github.com/tandasat/HyperPlatform/tree/4dce880bd5781d73412da1b77faeeb54e114cf93
https://github.com/tandasat/EopMon/commit/80de8fab827ac1496bab626418fb7dfc29e570b4

**Comment by shsirk** [comment]
Thank you!
