### ISSUE TITLE
PatchGuard triggers BSOD when manual mapping Hypervisor

### ISSUE THREAD

**Issue by koemeet** [tandasat/HyperPlatform#44]
### Description

When you manual map an empty hypervisor (just setting up the VMM and pinging the VM once) PatchGuard seems to trigger `CRITICAL_STRUCTURE_CORRUPTION` with `Kernel notification callout modification` (arg4: 0x18). This is without modifying anything in the kernel, just an empty hypervisor. It seems very weird that PG would trigger just because a system thread is doing virtualization without being linked in the kernel module list. 

It doesn't seem to be caused by initializing the CPU's, since if I remove the `VmInitialization();` call from the `DriverEntry`, PG is still triggered.

I have tested the same hypervisor by signing it and loading it normally. There hasn't been a BSOD in over 4 hours. Longest I lasted with the manual mapped loading is ~60 minutes.

> Note: I have removed all SEH handlers and references to the driver object.

Any ideas on why this may happen or help me point into a direction to help resolve this issue?

### Expected behavior

I would expect PatchGuard not to be triggered.

### Actual behavior

Manual mapping it causes a `CRITICAL_STRUCTURE_CORRUPTION`, `Kernel notification callout modification` BSOD.

### Steps to reproduce the problem

Setup an empty Hypervisor based on HyperPlatform and manual map it using Blackbones implementation (https://github.com/DarthTon/Blackbone).

### Specifications
- Commit: https://github.com/tandasat/HyperPlatform/commit/374db11ecefd1f00acccbc34fec6c1013e6f080c
- OS version: Microsoft Windows [Version 10.0.14393]

- Architecture: x64

- Hardware: Physical

- Details:

```
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

CRITICAL_STRUCTURE_CORRUPTION (109)
This bugcheck is generated when the kernel detects that critical kernel code or
data have been corrupted. There are generally three causes for a corruption:
1) A driver has inadvertently or deliberately modified critical kernel code
 or data. See http://www.microsoft.com/whdc/driver/kernel/64bitPatching.mspx
2) A developer attempted to set a normal kernel breakpoint using a kernel
 debugger that was not attached when the system was booted. Normal breakpoints,
 "bp", can only be set if the debugger is attached at boot time. Hardware
 breakpoints, "ba", can be set at any time.
3) A hardware corruption occurred, e.g. failing RAM holding kernel code or data.
Arguments:
Arg1: a39fde59804ae530, Reserved
Arg2: b3b6eadfd2ccc1c2, Reserved
Arg3: 0000000000000006, Failure type dependent information
Arg4: 0000000000000018, Type of corrupted region, can be
	0 : A generic data region
	1 : Modification of a function or .pdata
	2 : A processor IDT
	3 : A processor GDT
	4 : Type 1 process list corruption
	5 : Type 2 process list corruption
	6 : Debug routine modification
	7 : Critical MSR modification

Debugging Details:
------------------

ADDITIONAL_DEBUG_TEXT:  

Use '!findthebuild' command to search for the target build information.

If the build information is available, run '!findthebuild -s ; .reload' to set symbol path and load symbols.

MODULE_NAME: nt

FAULTING_MODULE: fffff8015cc94000 nt

DEBUG_FLR_IMAGE_TIMESTAMP:  595f2981

BUGCHECK_STR:  0x109

CUSTOMER_CRASH_COUNT:  1

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

CURRENT_IRQL:  0

LAST_CONTROL_TRANSFER:  from 0000000000000000 to fffff8015cde3960

STACK_TEXT:  
ffff9f00`ec7e4fb8 00000000`00000000 : 00000000`00000109 a39fde59`804ae530 b3b6eadf`d2ccc1c2 00000000`00000006 : nt+0x14f960


STACK_COMMAND:  kb

FOLLOWUP_IP: 
nt+14f960
fffff801`5cde3960 48894c2408      mov     qword ptr [rsp+8],rcx

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  nt+14f960

FOLLOWUP_NAME:  MachineOwner

IMAGE_NAME:  ntoskrnl.exe

BUCKET_ID:  WRONG_SYMBOLS
```

**Comment by koemeet** [comment]
I have come to believe it may be related to `PowerCallbackInitialization` and `HotplugCallbackInitialization`. For me it is fine to not support power callbacks and cpu hotplugging. I haven't got a BSOD in over well 2 hours. Any idea @tandasat why this could trigger a PG bsod when manual mapped?

**Comment by tandasat** [comment]
Hi thanks for the detailed report. 

I suspect the cause might be in a way Blackbones loads a driver; there is an open issue reporting occurrences of CRITICAL_STRUCTURE_CORRUPTION.
https://github.com/DarthTon/Blackbone/issues/109

What I *guess* from your comments is that Blackbones loads a driver without legitimately mapping an image. Then. the driver (HyperPlatform.sys) registers callbacks with those functions whose callback functions are outside any image files. I would not surprise if KPP does not like callback functions outside driver image files.

**Comment by koemeet** [comment]
In this case it is unrelated to Blackbone itself. But your last statement seems to be true. After removing these callbacks KPP no longer finds anything to bugcheck for! Do you by any chance know how many hours have to pass in order to say it is PG safe?

**Comment by tandasat** [comment]
There is no way to guarantee that it is KPP safe if we do anything undocumented (I thought of that the latest version of PG started to detect virtualization when I see this report, to be honest). 

But if I have to say something, I would say that if I repeated a cycle of rebooting and waiting an hour 10-20 times, I would get *some* confidence (since KPP decides what aspects to check at the system boot time, you must reboot and wait some times). But again, it does not guarantee anything; just verifying that a chances of getting a bugcheck is not that high (with the current version of PG).

NB: You could use VMware and launch multiple VMs to do this kind of verification if you are going to test.

**Comment by koemeet** [comment]
Alright, good to know! I am gonna close this since this issue seems to be resolved and is documented well in the comments.
