### ISSUE TITLE
Trigger PatchGuard (GDT)

### ISSUE THREAD

**Issue by yourapple** [tandasat/HyperPlatform#51]
Hi~

 I found that the default project will trigger PatchGuard on win7 (x64) SP1, and the following is part of the blue screen. It seems that the information of GDT is detected.

The test way is to only load the drive, and then wait a moment to trigger.

CRITICAL_STRUCTURE_CORRUPTION (109)
This bugcheck is generated when the kernel detects that critical kernel code or
data have been corrupted. There are generally three causes for a corruption:

A driver has inadvertently or deliberately modified critical kernel code
or data. See http://www.microsoft.com/whdc/driver/kernel/64bitPatching.mspx
A developer attempted to set a normal kernel breakpoint using a kernel
debugger that was not attached when the system was booted. Normal breakpoints,
"bp", can only be set if the debugger is attached at boot time. Hardware
breakpoints, "ba", can be set at any time.
A hardware corruption occurred, e.g. failing RAM holding kernel code or data.
Arguments:
Arg1: a3a039d896da8849, Reserved
Arg2: b3b7465ee958c4b3, Reserved
Arg3: fffff80000b95000, Failure type dependent information
Arg4: 0000000000000003, Type of corrupted region, can be
0 : A generic data region
1 : Modification of a function or .pdata
2 : A processor IDT
3 : A processor GDT
4 : Type 1 process list corruption
5 : Type 2 process list corruption
6 : Debug routine modification
7 : Critical MSR modification
Debugging Details:
BUGCHECK_STR: 0x109

DEFAULT_BUCKET_ID: VISTA_DRIVER_FAULT

PROCESS_NAME: System

CURRENT_IRQL: 2

LAST_CONTROL_TRANSFER: from fffff80003fcdd92 to fffff80003ede490

SYMBOL_ON_RAW_STACK: 1

STACK_ADDR_RAW_STACK_SYMBOL: fffff880047bcfc0

STACK_COMMAND: dds 047BCFC0-0x20 ; kb

**Comment by tandasat** [comment]
Very interesting. I was able to reproduce the issue on my side. It seems it is related to NTVDM, so bug check should not occur on Windows 8, thought I have not verified it yet.

**Comment by yourapple** [comment]
I tested win10 (x64) 14393 yesterday, as well as triggering PatchGuard.

Win8 I'll test it to you today.

**Comment by yourapple** [comment]
Win8 also triggers the PatchGuard.

The test system is Win8.1 (x64 9600.16384)

**Comment by tandasat** [comment]
Thanks for helping to diagnose. It seems that you can avoid bug check by disabling LDT/GDT access VM-exit as workaround.
```
  vm_procctl2_requested.fields.descriptor_table_exiting = true;   // set false if not needed 
```

**Comment by yourapple** [comment]
Yes, I do that right now.



I don't need this for the time being, or I would like to thank you for writing such a great VT framework.

**Comment by tandasat** [comment]
CC: @asamy as ksm is missing this behaviour too.
