### ISSUE TITLE
Unexpected KMODE trap (only on Win 10 CU) when switching to guest CR3 in vmexit

### ISSUE THREAD

**Issue by koemeet** [tandasat/HyperPlatform#52]
### Description
I need to translate the `guest_context->ip` to its physical address inside the software breakpoint vm-exit, so in order to do this I need to switch to the guest CR3 and then call `UtilPaFromVa(guest_context->ip);`. This succeeds on Windows 7 and Windows 10 AU, but fails on Windows 10 CU (version 1709, 16299.309). When you try to do the following in any VM-EXIT it causes a `UNEXPECTED_KERNEL_MODE_TRAP` bugcheck:

```cpp
auto oldcr3 = __readcr3();
__writecr3(UtilVmRead(VmcsField::kGuestCr3));
// do stuff in virtual space of guest
__writecr3(oldcr3);
```

I tested the same on Windows 7 SP1 and Windows 10 AU (version 1607, 14393.0). It works as expected on these operating systems and no bugcheck happens.

### Expected behavior
Expected behaviour would be that upon vm-exit you are able to switch to the guest cr3 on Windows 10 CU without having a bugcheck.

### Actual behavior
On windows 10 CU, inside a vm-exit, when you switch to the guest CR3 it triggers a `UNEXPECTED_KERNEL_MODE_TRAP` bugcheck. This bugcheck does not occur on older windows versions such as AU and Windows 7.

### Steps to reproduce the problem
Add the following code above the `VmmpHandleVmExit(&guest_context, exit_reason);` call inside `vmm.cpp` on Windows 10 CU (version 1709):

```cpp
auto oldcr3 = __readcr3();
__writecr3(UtilVmRead(VmcsField::kGuestCr3));
__writecr3(oldcr3);

VmmpHandleVmExit(&guest_context, exit_reason);
```

### Specifications
- Commit #d14633cf1b035467adb87017027948f9fca241b4

- OS version: Microsoft Windows [Version 10.0.16299.309]

- Architecture: x64

- Hardware: VMWare 11 & Physical

- Details:
Tested the above scenario on VMWare and a physical machine running Microsoft Windows [Version 10.0.16299.309].

```
UNEXPECTED_KERNEL_MODE_TRAP (7f)
This means a trap occurred in kernel mode, and it's a trap of a kind
that the kernel isn't allowed to have/catch (bound trap) or that
is always instant death (double fault).  The first number in the
bugcheck params is the number of the trap (8 = double fault, etc)
Consult an Intel x86 family manual to learn more about what these
traps are. Here is a *portion* of those codes:
If kv shows a taskGate
        use .tss on the part before the colon, then kv.
Else if kv shows a trapframe
        use .trap on that value
Else
        .trap on the appropriate frame will show where the trap was taken
        (on x86, this will be the ebp that goes with the procedure KiTrap)
Endif
kb will then show the corrected stack.
Arguments:
Arg1: 0000000000000008, EXCEPTION_DOUBLE_FAULT
Arg2: fffff80033869e50
Arg3: ffff8d806c89ecc0
Arg4: fffff805e8b5ee8d

Debugging Details:
------------------


DUMP_CLASS: 1

DUMP_QUALIFIER: 400

BUILD_VERSION_STRING:  10.0.16299.309 (WinBuild.160101.0800)

SYSTEM_MANUFACTURER:  VMware, Inc.

VIRTUAL_MACHINE:  VMware

SYSTEM_PRODUCT_NAME:  VMware7,1

SYSTEM_VERSION:  None

BIOS_VENDOR:  VMware, Inc.

BIOS_VERSION:  VMW71.00V.6997262.B64.1710270607

BIOS_DATE:  10/27/2017

BASEBOARD_MANUFACTURER:  Intel Corporation

BASEBOARD_PRODUCT:  440BX Desktop Reference Platform

BASEBOARD_VERSION:  None

DUMP_TYPE:  2

BUGCHECK_P1: 8

BUGCHECK_P2: fffff80033869e50

BUGCHECK_P3: ffff8d806c89ecc0

BUGCHECK_P4: fffff805e8b5ee8d

BUGCHECK_STR:  0x7f_8

TRAP_FRAME:  fffff80033869e50 -- (.trap 0xfffff80033869e50)
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=0000000106410001 rbx=0000000000000000 rcx=0000000106410001
rdx=ffffaf09f3d3d200 rsi=0000000000000000 rdi=0000000000000000
rip=fffff805e8b5ee8d rsp=ffff8d806c89ecc0 rbp=00007ffb6b13904d
 r8=ffffaf09f3d3d388  r9=0000000000006802 r10=0000000000000000
r11=0000003c21d7f058 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up di ng nz na po nc
Hypervisor+0xee8d:
fffff805`e8b5ee8d 488bcb          mov     rcx,rbx
Resetting default scope

CPU_COUNT: 2

CPU_MHZ: 1068

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 9e

CPU_STEPPING: 9

CPU_MICROCODE: 6,9e,9,0 (F,M,S,R)  SIG: 70'00000000 (cache) 70'00000000 (init)

CUSTOMER_CRASH_COUNT:  1

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

PROCESS_NAME:  dwm.exe

CURRENT_IRQL:  2

ANALYSIS_SESSION_HOST:  KOEMEET-PC

ANALYSIS_SESSION_TIME:  03-28-2018 22:47:15.0995

ANALYSIS_VERSION: 10.0.16299.15 amd64fre

BAD_STACK_POINTER:  ffff8d806c89ecc0

LAST_CONTROL_TRANSFER:  from fffff80031788529 to fffff80031775510
```

**Comment by tandasat** [comment]
Does this reproduce where ever the code snippet is added to VM-exit handling code? `VmmpHandleGdtrOrIdtrAccess` already has the same code already and I believed it worked on Win10 CU.

**Comment by koemeet** [comment]
@tandasat I noticed that in `VMX` exits it also works fine (VMCALL etc.). The bug also happens if you only putp this code in the `CPUID` exit.

**Comment by koemeet** [comment]
I can confirm that the following code inside `VmmpHandleGdtrOrIdtrAccess` works fine on Win 10 CU:

```cpp
const auto guest_cr3 = UtilVmRead(VmcsField::kGuestCr3);
const auto vmm_cr3 = __readcr3();
 __writecr3(guest_cr3);
```

**Comment by tandasat** [comment]
I quickly looked into why it bug checked. I believe the code is hitting the rule `#GP .. If an attempt is made to write a 1 to any reserved bit in CR3.` described under `MOV—Move to/from Control Registers`. Changing lower 12bits of CR3 when the PCID Enable bit of CR4 is clear would meet that condition as PCID is disabled and those lower bits would be treated as reserved (or must be zero bits). 

Try temporarily enable the PCID bit while changing CR3.

**Comment by koemeet** [comment]
@tandasat I have tested your proposal and PCID is always enabled when the failing vmexits happen. I do have valuable logs which could help identifying the problem:

I logged the real CR3 of a certain process in Windows, which was `00000000B0200002`. Then I triggered an exception vmexit from within this same process and when I read the guest cr3 using `UtilVmRead64(VmcsField::kGuestCr3));` it gives me `00000000B0D00001`. So in the end I have:

```
Real CR3    = 00000000B0200002
CR3 in exit = 00000000B0D00001
```

It doesn't seem to be an issue with any reserved bits or PCID, but rather an incorrect cr3 read of the guest?

**Comment by koemeet** [comment]
In case someone is stumbling upon the same problem, for now you can use this temporary solution to switch to the guest cr3 in the failing vmexits:

```cpp
auto process = reinterpret_cast<__int64>(IoGetCurrentProcess());
auto cr3 = *reinterpret_cast<__int64*>(process + 0x28);

const auto old_cr3 = __readcr3();
__writecr3(cr3);
// working fine in exception vmexit
__writecr3(old_cr3);
```

**Comment by tandasat** [comment]
The issue was that `VmcsField::kGuestCr3` could store an user-mode CR3 (`_KPROCESS::UserDirectoryTableBase`) which could not be used in the kernel-mode when VM-exit occurred in the user-mode. 

For example, if a process whose kernel address space is shadowed due to the Meltdown patch, its CR3 value does not map full kernel address space when it is running in the user-mode. When such a process triggers VM-exit from the user-mode (eg, via `CPUID` or `SIDT`), a processor stores the user-mode CR3 into `kGuestCr3`, instead of a kernel-mode CR3. If a VMM tries to load such value, it would be missing some critical kernel virtual address space and trigger exceptions causing the bug check.

To address this issue, you have to get the kernel CR3 in VM-exit handling code. I added `VmmpGetKernelCr3` you can use for that work.

**Comment by koemeet** [comment]
Gg. Thats clears some things up! Thanks for taking time to explain the situation. 🍺

**Comment by tandasat** [comment]
You are welcome 👍
