### ISSUE TITLE
Reading memory from userland (guest)

### ISSUE THREAD

**Issue by tdavis165** [tandasat/HyperPlatform#56]
### Description

Hello, I've been working on a small project trying to achieve something in the system out of curiosity and have been trying to read some guest memory from lsass.exe, but I am having problems figuring out how to translate the virtual memory into physical memory so that I can correctly read the memory from the process.

I have tried utilizing the cr3 register to help me achieve this but have had no luck.

### Expected behavior

To be able to translate the virtual memory into physical memory and read the guest os's memory from lsass.exe

Thanks for reading.

**Comment by tandasat** [comment]
Hi, if I understand you right, you should be able to read lsass.exe's process memory, by just switching the current CR3 to the lsass's one and using the virtual address (VA) you already have. You do not have to go through VA to physical address (PA) translation in your code; the processor does this.

Just as an answer to your original question, it is bit complicated depending on what type of VA you want to translated to PA. For example, VA can be backed by a paged-file, physical pages shared by multiple processes. This article gives your nice summary of how VA translation works on Windows. If you are in a hypervisor, you should not call kernel APIs, so you would have to implement logic similar to this by hand if you absolutely need it.
http://blog.rekall-forensic.com/2014/10/windows-virtual-address-translation-and.html
