### ISSUE TITLE
about VmmpHandleRdtsc

### ISSUE THREAD

**Issue by strivexjun** [tandasat/HyperPlatform#58]
https://github.com/tandasat/HyperPlatform/blob/c0403b2f80252bf6930665ed06d80d6d4b00798f/HyperPlatform/vmm.cpp#L446

### Specifications
Build: VS2017+WDK10
OS：Win7 x64 Build 7601
VirutualMachine:  VMware 14 pro

### Description
Hello!

When I successfully loaded HyperPlatform, VmmpHandleCpuid were all right, but could you tell me why this VmmpHandleRdtsc would not trigger?

**Comment by tandasat** [comment]
Hi, that is because `rdtsc_exiting` is not enabled by default (for performance). Please set true to the field in `VmxProcessorBasedControls` for receiving RDTSC VM-exit.

**Comment by strivexjun** [comment]
thank very mach.
