### ISSUE TITLE
Ia32MtrrDefaultTypeMsr  

### ISSUE THREAD

**Issue by a132266** [tandasat/HyperPlatform#59]
(Please use this issue template for a bug report. You need not use it for any other type of issues.)

### Description

(Please describe)
kIa32MtrrDefType  intel difference？

### Expected behavior
![image](https://user-images.githubusercontent.com/41984214/52176603-edb15680-27ef-11e9-9fdd-000cbbc05698.png)

(Please describe)

### Actual behavior

(Please describe)

### Steps to reproduce the problem

(Please describe if applicable)

### Specifications
- Commit (eg, 2099af7): (Please fill in)

- OS version (ie, output of the "ver" command, or N/A): (Please fill in)

- Architecture: (Please choose: x86, x64, Both, or N/A)

- Hardware (eg, Physical, VMware 14, Bochs, or N/A): (Please fill in)

- Details: (Please describe)

--
NOTE: The Details section may include related log files, crash dump files,
impact/importance of the issue, proposed fix and anything you may think useful
for fixing the issue.

It is hugely helpful and speeds up investigation of a bug check or a hang issue
if the following files are provided:
- a Debug build version of a compiled SYS file and a PDB file
- a full set of source code used to build the SYS file if it has been modified
- a log file (i.e., C:\Windows\HyperPlatform.log)
- a system crash dump file (i.e., C:\Windows\MEMORY.DMP)

GitHub does not support attaching of any binary files into issues. You may use
any free file hosting services, however. Here are some of those services:
- OneDrive
- DropBox
- GoogleDrive
- Sendspace
- Mega.nz

**Comment by tandasat** [comment]
I think @a132266 is seeing that the definitions in the table and one in the `11.11.2.1 IA32_MTRR_DEF_TYPE MSR` section are different. I would suggest 
![image](https://user-images.githubusercontent.com/1620923/52177941-2106cd80-277d-11e9-98d3-4917e465a789.png)

I would suggest asking at the Intel forum (https://software.intel.com/en-us/forums/platform-and-technology-discussion). They are usually rather prompt.

**Comment by a132266** [comment]
Thanks for answers
