### ISSUE TITLE
Performance in VMWare

### ISSUE THREAD

**Issue by arnerak** [tandasat/HyperPlatform#62]
Hello,
while HyperPlatform performs great on my PC, i have performance issues in VMWare. It takes 2-3 minutes alone to initialize the hypervisor. I have disabled the performance monitor, but that did not have an impact. Is this normal or is there a way to improve the performance inside VMWare?

**Comment by tandasat** [comment]
That is possible to take that long on VMware depending on load (eg, other VMs running etc) but 2-3 minutes is certainly unusual. In my experience, disabling kernel debugger makes it a lot faster. If you have not tried, please do so. Otherwise, possibly disabling logging could speed it up.
