### ISSUE TITLE
detect hypervisor running

### ISSUE THREAD

**Issue by InvisK** [tandasat/HyperPlatform#65]
hello, im using hyperplatform for my alternative method to make security things, but in some computers which already have a vm running i get problem like bluescreen, hanging,... i think it's not because hyperplatform, just because thier hypervisor is not so optimized for nested vm, so how i can detect if a hypervisor already ran in a system ? thank you for the good project.

**Comment by rianquinn** [comment]
This should get you started:
https://theinvisiblethings.blogspot.com/2007/08/virtualization-detection-vs-blue-pill.html

There are also open source projects that can do this based on the hypervisor's signature:
https://github.com/dmbaturin/hvinfo

Another way to do this would be to read CPUID 0x40000000. If you get a response, there is a hypervisor running.

**Comment by rianquinn** [comment]
Oh, and you could always read out CR4. If VXE is enabled, a hypervisor is likely running. Note that most of these would not work if you are dealing with a rootkit, so in those cases you need to go down the timing route. We have some work related to that with ECR:
https://github.com/ainfosec/ecr_toolkit

**Comment by tandasat** [comment]
Thank you for sharing the techniques. I doubt the CPUID 0x40000000 or the VME bit helps to detect whether the other hypervisor is already running in *the host*. Those are great indicators for the guests to detect there is a hypervisor but not for the host. (you can tell Hyper-V is running as the host is actually on VCPU.)

I might look into detection of virtualization software, such as existence of certain services or drivers but, I do not have any better suggestion off the top of my head. It could also be interesting to update HpyerPlatform to handle the situation but it might be more work than you want for the problem you have.

**Comment by rianquinn** [comment]
I agree 100% with the host OS argument. Not many hypervisors support this, and the ones that do like HyperPlatform, SimpleVisor, Bareflank, etc... don't use 0x40000000 to advertise their existence. HyperV does, even when it is under the host OS, but that is an exception. To detect this type of hypervisor you would need to treat it as a rootkit, and in those cases, timing is your best bet and should be pretty simple as most operating systems provide nanosecond wallclocks, so you can simply execute CPUID a million times and threshold the value. Not too hard.

**Comment by InvisK** [comment]
hello, thanks for the helps, finally i found a snippet that could solve it, here for who need it : https://gist.github.com/InvisK/8d15b6f23f20e4af95fe5b16be2bbbae

**Comment by tandasat** [comment]
Thanks for sharing this @InvisK. Looks like this is VM detection within a guest and not from the same host OS. I misunderstood your ask; I thought you were trying to avoid coexisting with other hypervisor. 

Glad to find a solution either way. Closing this.

**Comment by InvisK** [comment]
@tandasat oh im just tested it and it's working to detect hyperplatform running in same host OS(return false before start hyperplatform and return true after hyperplatform start successfully), maybe working for both guest/host ? :D
