### ISSUE TITLE
A link error against __stdio_common_vswprintf() occurs with RtlStringCchPrintfW()

### ISSUE THREAD

**Issue by tandasat** [tandasat/HyperPlatform#8]
Using RtlStringCchPrintfW() leads a link error with __stdio_common_vswprintf() when a project setting is changed to enable STL according with the User's Document. As RtlStringCchPrintfA() is already supported, -W() should also be able to used.

**Comment by esoterix** [comment]
Proper solution is to add the "_NO_CRT_STDIO_INLINE" preprocessor definition.
