### ISSUE TITLE
The original has not been modified,Enable the blue screen of cpuid!

### ISSUE THREAD

**Issue by baby0o01999** [tandasat/HyperPlatform#84]
The original has not been modified,Enable the blue screen of cpuid!

-----------------------------------------------------------------------------------------

Microsoft (R) Windows Debugger Version 10.0.19494.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Windows\Minidump\090621-13265-01.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

WARNING: Whitespace at end of path element

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
OK                                             F:\DebugSymbols
WARNING: Whitespace at end of path element
Symbol search path is: srv*;F:\DebugSymbols;SRV*f:\DebugSymbols* http://msdl.microsoft.com/download/symbols 
Executable search path is: 
WARNING: Whitespace at end of path element
Windows 10 Kernel Version 18362 MP (16 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 18362.1.amd64fre.19h1_release.190318-1202
Machine Name:
Kernel base = 0xfffff807`4b600000 PsLoadedModuleList = 0xfffff807`4ba432b0
Debug session time: Mon Sep  6 18:45:25.689 2021 (UTC + 11:00)
System Uptime: 0 days 0:02:49.025
Loading Kernel Symbols
...............................................................
................................................................
................................
Loading User Symbols
Loading unloaded module list
.......
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify timestamp for HyperPlatform.sys
nt!KeBugCheckEx:
fffff807`4b7bc8a0 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:ffffbb0f`e20f2c10=00000000000000e2
6: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

MANUALLY_INITIATED_CRASH (e2)
The user manually initiated this crash dump.
Arguments:
Arg1: 0000000000000003
Arg2: 0000000000000033
Arg3: ffffbb0fd6f63dd0
Arg4: 0000000000000000

Debugging Details:
------------------

*** WARNING: Unable to verify timestamp for win32k.sys

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 4

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on E5_1

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 5

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 70

    Key  : Analysis.System
    Value: CreateObject

BUGCHECK_CODE:  e2

BUGCHECK_P1: 3

BUGCHECK_P2: 33

BUGCHECK_P3: ffffbb0fd6f63dd0

BUGCHECK_P4: 0

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  cpuz_x64.exe

BAD_STACK_POINTER:  ffffbb0fe20f2c08

STACK_TEXT:  
ffffbb0f`e20f2c08 fffff807`52a313fe : 00000000`000000e2 00000000`00000003 00000000`00000033 ffffbb0f`d6f63dd0 : nt!KeBugCheckEx
ffffbb0f`e20f2c10 00000000`000000e2 : 00000000`00000003 00000000`00000033 ffffbb0f`d6f63dd0 00000000`00000000 : HyperPlatform+0x13fe
ffffbb0f`e20f2c18 00000000`00000003 : 00000000`00000033 ffffbb0f`d6f63dd0 00000000`00000000 00000000`00000000 : 0xe2
ffffbb0f`e20f2c20 00000000`00000033 : ffffbb0f`d6f63dd0 00000000`00000000 00000000`00000000 00000000`d5a00000 : 0x3
ffffbb0f`e20f2c28 ffffbb0f`d6f63dd0 : 00000000`00000000 00000000`00000000 00000000`d5a00000 fffff807`52a31565 : 0x33
ffffbb0f`e20f2c30 00000000`00000000 : 00000000`00000000 00000000`d5a00000 fffff807`52a31565 ffffbb0f`e9785568 : 0xffffbb0f`d6f63dd0

SYMBOL_NAME:  HyperPlatform+13fe

MODULE_NAME: HyperPlatform

IMAGE_NAME:  HyperPlatform.sys

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  13fe

FAILURE_BUCKET_ID:  0xE2_STACKPTR_ERROR_HyperPlatform!unknown_function

OS_VERSION:  10.0.18362.1

BUILDLAB_STR:  19h1_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {2cafce20-8d68-ef58-3a52-24610b0872fd}

Followup:     MachineOwner
---------

**Comment by tandasat** [comment]
Can you please resolve the symbol for me. Thanks

**Comment by baby0o01999** [comment]
> Can you please resolve the symbol for me? Thanks

https://send.fdab.se/download/73ccf366b20d65bc/#TRVA4ZWhUa3S-FOMGc4NFQ

**Comment by tandasat** [comment]
Increase `kEptpNumberOfPreallocatedEntries`. `preallocated_entries` is used up.
