### ISSUE TITLE
error 1284: Class "Sample" is reserved for use by Microsoft.

### ISSUE THREAD

**Issue by SiyerBOBO** [tandasat/HyperPlatform#88]
![image](https://user-images.githubusercontent.com/47243555/150296964-3e859d40-7603-48f6-be35-b3ee7b2c8908.png)
error 1284: Class "Sample" is reserved for use by Microsoft.
error 1285: Cannot specify [ClassInstall32] section for Microsoft-defined class.
What should I do? I can't find any information on how to solve the problem.

**Comment by SiyerBOBO** [comment]
![image](https://user-images.githubusercontent.com/47243555/150297304-83bbf6be-24bc-47c1-a126-c4c55fb230cb.png)

**Comment by tandasat** [comment]
You may delete the INF file all together. I pushed local changes that required for building the project with the latest VS2019.

**Comment by SiyerBOBO** [comment]
As a new driver developer, does inf file deletion have no impact on the whole project? (It does compile and run properly after deleting INF files)

**Comment by SiyerBOBO** [comment]
I have received your project update, thank you for your attention.

**Comment by kkent030315** [comment]
You can specify any class names (e.g., `Class=MyClass`) and you also have to create ClassGUID.
To generate GUID, you can simply open PowerShell and execute `New-Guid` as follows:

```ps
PS C:\Users > New-Guid

Guid
----
a89a32f3-cf95-4832-a570-8e97f8136df6
```

.inf is mainly used for production release(for example, getting signed by Microsoft needs valid .inf), so it's not mandatory for the hobby driver developments, and no impacts at all.

You can simply delete .inf file and disable `Project Configuration -> Inf2Cat -> Run Inf2Cat`.

![image](https://user-images.githubusercontent.com/37926134/150388548-a2788c62-88a6-4868-9371-23cca4a5fb9f.png)
(Change it to "No")

**Comment by tandasat** [comment]
Thanks for commenting on this. This is right. 

I am closing the issue.
